### ISSUE TITLE
contact request tweaks

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android#1990]
- [x] is the "Chat with ..." line really required? all information are already shown on the screen - it is probably from the old api where we have shown an alter without much context. also, it pop up for mailinglist and one-to-ones only, not for groups. on ios, it was never there and it feels intuitive, at least from my point of view. maybe just drop it and see how it works out.

- [ ] while the accept/block buttons look nice, ui-wise, they do not really fit into the rest of the app nor to material design (they look like ios). maybe use buttons similar to the rest of the app (as in the welcome screen, the fab-button). not a major thing, however, maybe it is also good to play around a bit longer.

- [ ] there was some possible slowness @Hocuri is checking out, cmp. #1994

- [x] contact requests should not be shown in "bold" as for fresh messages

- [x] ~~do we need a badge counter for "Request" - it was added for ios but not for android, cmp https://github.com/deltachat/deltachat-ios/issues/1306 - i do not have a strong opinion on that, however, maybe it is easier to drop it on ios.~~
EDIT: that part is solved, also ios skips the badge now

- [x] ~~wrt wording of "Accept": we already have the string "Start chat" - maybe that is even better, and it is more clear what finally happen (came over that as i do not like the german translations "Akzeptieren" or "Annehmen" - or what else can we use?)~~  
EDIT: let's leave that as is for now and see how that works. it is also the wording used in signal.

- [x] done in core: on upgrade, move old/noticed contact requests to "archived chats" - otherwise, after upgrade ppl may be an otherwise clean chatlist spammed with hundreds of pretty old chats, see https://github.com/deltachat/deltachat-core-rust/issues/2562

- [x] also changed in core: remove badge counter from "Archived Chats" cell, see https://github.com/deltachat/deltachat-core-rust/pull/2566 for reasoning

- [x] add "Archived Chats" to menu

**Comment by Hocuri** [comment]
>  is the "Chat with ..." line really required? all information are already shown on the screen - it is probably from the old api where we have shown an alter without much context. also, it pop up for mailinglist and one-to-ones only, not for groups. on ios, it was never there and it feels intuitive, at least from my point of view. maybe just drop it and see how it works out.

I mostly followed Signal, [and Signal had such a line](https://support.signal.org/hc/en-us/articles/360007459591-Signal-Profiles-and-Message-Requests), so I put it here, too. Although Signal's line is a bit more informative, our line just says "Chat with xy", which is kinda unnecessary. For mailing lists, I think that it's nice that the user is asked "_show_ mailing list xy?", as it's just about whether it's shown. Although I didn't ask any users or so about this.

**Comment by adbenitez** [comment]
IMHO it is better to remove the "chat with X?" question, even in mailing list it says "mailing list" in the top bar, and if the name+address is really long, for example yggmail addresses, this will look pretty ugly

**Comment by r10s** [comment]
yip, i would also remove it, when questions pop up, we can add sth., however, that should be less redundant then

**Comment by r10s** [comment]
> about the buttons I think they look nice

yip, as said, they look nice, however, this is not material design, cmp. https://material.io/components/buttons

> besides the welcome button I could not find other button to compare

there are similar buttons at group creation - and also, we have the fab-button. the thing is, that i would avoid introducing too many button styles to have an internal consistency.

we can re-style, of course, but that should affect all buttons then.

**Comment by adbenitez** [comment]
using "contained" style has some decisions to do in dark mode, using "outlined" will be pretty similar to what we ave now, but maybe still too different to buttons everywhere else

**Comment by adbenitez** [comment]
btw, Telegram also doesn't show any "chat with X" or similar, just the buttons

**Comment by Hocuri** [comment]
We only break between the welcome button and the contact request buttons, and I don't think users will even notice this very small inconsistency, I think that users usually care less about consistency than developers. And it's not that the buttons look totally different from Material Design, they are rather a mixture of the three types. And currently we are only using a single button style as far as I can see, so the variety won't hurt I think (btw I took the design from Signal, who of course have a different overall style than DC though)

And yes, we can remove the "Chat with..." line and add some explanatory text there in case users have questions.

**Comment by r10s** [comment]
the buttons are nothing urgent, indeed.

however, they do not really fit to the rest of the app, signal has a completely different overall style. maybe that inconsistency is not much noticeable alone, however, inconsistencies may sum up and result in an overall not-so-good-looking app - whereas each element as such is nice. and as said, the buttons are used at more places than just "welcome", the colors are cited, there is the send button and so on.

in general, it is a good idea to have basic styles that are used throughout the app, so that there is no discussion on each and every button and control ;) i really like to avoid that on android.

**Comment by r10s** [comment]
well, closing this issue for now, we can tweak the buttons at some later point, there are more important issues :)
