### ISSUE TITLE
[consolidating] situations with high power battery usage / drain

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android#298]
Not every user is affected, in fact many devices that have only deltachat installed, and no other Messenger, have a very low and barely noticeable battery usage. However some users and devices, are affected by specific higher power usage situations.

This issue is to post (identify and then fix) the cases in which deltachat is too active (possibly looping) and unnecessarily draining the battery.

 

- [ ] after sending message exceeding the server's max. size (looping) https://github.com/deltachat/deltachat-android/issues/102
- [ ] circumstances where the network connection is very bad (for example when traveling by train) https://github.com/deltachat/deltachat-android/issues/297
- [ ] the latter may be related to (not) properly stopping/re-starting (after waiting a bit) all activity according to network state changes https://github.com/deltachat/deltachat-core/issues/84
- [ ] scanning many GB of Data every 30 minutes? on some IMAP servers? (didn't find this old issue from a gmail user anymore)

**Comment by g6094199** [comment]
+1

i checked the related topis but i dont think any of them fits my drain.
anyway it starts with 0.17.3 imho. i run LineageOS on an S5. before i never saw such battery drain from DC. when i kill the DC service the drain is gone.

**Comment by testbird** [comment]
Hi, If you manage to get the app into that state again, you could attach the log (as explained in https://github.com/deltachat/deltachat-android/issues/new).

**Comment by g6094199** [comment]
easy...happens on every start...


> © 2017, 2018 Delta Chat contributors
> 
> Chats: 4
> Chat messages: 1195
> Messages in mailbox: 17
> Contacts: 91
> Database=/data/user/0/com.b44t.messenger/files/messenger.db, dbversion=39, Blobdir=/data/user/0/com.b44t.messenger/files/messenger.db-blobs
> 
> displayname=0
> configured=1
> config0=odysseus_held_der_antike@web.de 0:***:0:0 0:0:0:0 0
> config1=odysseus_held_der_antike@web.de odysseus_held_der_antike:***:imap.web.de:993 odysseus_held_der_antike:***:smtp.web.de:587 AUTH_NORMAL IMAP_SSL SMTP_STARTTLS
> mdns_enabled=1
> e2ee_enabled=1
> E2EE_DEFAULT_ENABLED=1
> Private keys=1, public keys=6, fingerprint=
> AA9F 9C0C 81AB EA96 9E4C
> 975F 0E17 58BF F197 75DD
> 
> Using Delta Chat Core v0.17.3, SQLite 3.22.0-ts1, libEtPan 1.7, OpenSSL 1.0.1t. Compiled May 20 2018, 15:00:16 for 32 bit usage.
> 
> Log excerpt:
> 
> 19:21:32 T2: Attaching C-thread to Java VM...
> 19:21:32 T2: Attaching ok.
> 19:21:32 T2: Job thread entered.
> 19:21:32 T2: Job thread waiting for signal...
> 19:21:32 T1: Opened "/data/user/0/com.b44t.messenger/files/messenger.db" successfully.
> 19:21:32 T1: Signal job thread to wake up...
> 19:21:32 T2: Job thread checks for pending jobs...
> 19:21:32 T2: Executing job #32, action 900...
> 19:21:32 T2: Connecting to IMAP-server "imap.web.de:993" via SSL...
> 19:21:32 T1: Chatlist for search "" created in 8.418 ms.
> 19:21:33 T2: Connection to IMAP-server ok.
> 19:21:33 T2: Login to IMAP-server as "odysseus_held_der_antike"...
> 19:21:33 T2: IMAP-Login ok.
> 19:21:33 T2: IMAP-Capabilities: IMAP4rev1 CHILDREN ENABLE ID IDLE LIST-EXTENDED LIST-STATUS LITERAL+ MOVE NAMESPACE QUOTA SASL-IR SORT SPECIAL-USE THREAD=ORDEREDSUBJECT UIDPLUS UNSELECT WITHIN
> 19:21:33 T2: Starting IMAP-watch-thread...
> 19:21:33 T3: Attaching C-thread to Java VM...
> 19:21:33 T4: Attaching C-thread to Java VM...
> 19:21:33 T3: Attaching ok.
> 19:21:33 T3: IMAP-watch-thread started.
> 19:21:33 T4: Attaching ok.
> 19:21:33 T3: Fetching from all folders.
> 19:21:33 T4: IMAP-heartbeat-thread started.
> 19:21:33 T2: Job #32 done and deleted from database
> 19:21:33 T2: Executing job #1, action 800...
> 19:21:33 T2: Connecting to SMTP-server "smtp.web.de:587" via Socket...
> 19:21:33 T3: 0 mails read from "Chats" with 0 errors.
> 19:21:33 T2: Switching to SMTP-STARTTLS.
> 19:21:33 T3: 0 mails read from "Drafts" with 0 errors.
> 19:21:33 T3: Folder "Entwürfe" ignored.
> 19:21:34 T3: 0 mails read from "Gesendet" with 0 errors.
> 19:21:34 T3: 0 mails read from "INBOX" with 0 errors.
> 19:21:34 T2: Connection to SMTP-server ok.
> 19:21:34 T2: Login to SMTP-server as "odysseus_held_der_antike"...
> 19:21:34 T3: 0 mails read from "Papierkorb" with 0 errors.
> 19:21:34 T2: SMTP-Login ok.
> 19:21:34 T3: Init lastseenuid and attach it to UIDVALIDITY for folder "Postausgang".
> 19:21:34 T3: Folder "Postausgang" is empty.
> 19:21:34 T3: 0 mails read from "Postausgang" with 0 errors.
> 19:21:34 T3: 0 mails read from "Sent" with 0 errors.
> 19:21:34 T3: Folder "Trash" ignored.
> 19:21:34 T3: 0 mails read from "Unbekannt" with 0 errors.
> 19:21:34 T3: Folder "Unerwünscht" ignored.
> 19:21:34 T3: IDLE start...
> 19:21:37 T1: Message list for chat #12 created in 1.106 ms.
> 19:21:40 T1: Message list for chat #15 created in 3.332 ms.
> 19:21:57 T1: Signal job thread to wake up...
> 19:21:57 T1: Message list for chat #15 created in 3.236 ms.
> 19:21:57 T1: Chatlist for search "" created in 3.404 ms.
> 19:21:57 T1: Chatlist for search "" created in 2.529 ms.
> 19:21:57 T1: Message list for search "(null)" in chat #0 created in 0.037 ms.
> 19:21:57 T1: Message list for chat #15 created in 2.753 ms.
> 
> SDK_INT=25
> MANUFACTURER=samsung
> MODEL=SM-G900F
> APPLICATION_ID=com.b44t.messenger
> BUILD_TYPE=release
> ABI=arm
> ignoreBatteryOptimizations=0
> versionCode=520

**Comment by sniperle** [comment]
Same here huge battery drain with version 18.0 on 2 different phones (OnePlus 3T with LineageOS 15.1):

06-24 14:04:55.813 I/DeltaChat( 5586): IMAP-IDLE has data.
06-24 14:04:55.813 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:04:55.816 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:04:55.816 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:04:55.816 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:04:55.851 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:04:55.852 I/DeltaChat( 5586): IMAP-fetch done in 1 ms.
06-24 14:04:55.854 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:04:58.000 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:04:58.003 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:04:58.004 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:04:58.007 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:05:01.722 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:05:01.724 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:05:01.728 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:05:01.929 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:05:01.933 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:05:27.653 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:05:55.988 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:05:55.988 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:05:55.993 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:05:55.994 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:05:55.994 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:05:56.036 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:05:56.037 I/DeltaChat( 5586): IMAP-fetch done in 2 ms.
06-24 14:05:56.039 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:05:58.003 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:05:58.008 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:05:58.010 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:05:58.013 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:06:16.361 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:06:16.366 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:06:16.384 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:06:20.130 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:06:20.144 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:06:27.663 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:06:55.156 I/DeltaChat( 5586): IMAP-IDLE has data.
06-24 14:06:55.157 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:06:55.165 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:06:55.167 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:06:55.168 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:06:55.209 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:06:55.210 I/DeltaChat( 5586): IMAP-fetch done in 4 ms.
06-24 14:06:55.215 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:06:58.001 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:06:58.007 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:06:58.009 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:06:58.015 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:07:06.049 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:07:06.053 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:07:06.063 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:07:27.677 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:07:55.342 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:07:55.343 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:07:55.351 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:07:55.354 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:07:55.354 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:07:55.397 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:07:55.397 I/DeltaChat( 5586): IMAP-fetch done in 4 ms.
06-24 14:07:55.403 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:07:58.002 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:07:58.010 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:07:58.012 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:07:58.018 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:08:25.207 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:08:25.209 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:08:27.683 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:08:55.543 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:08:55.544 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:08:55.550 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:08:55.551 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:08:55.551 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:08:55.589 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:08:55.590 I/DeltaChat( 5586): IMAP-fetch done in 3 ms.
06-24 14:08:55.597 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:08:58.001 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:08:58.008 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:08:58.010 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:08:58.016 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:09:27.702 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:09:46.153 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:09:46.157 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:09:46.166 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:09:55.733 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:09:55.734 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:09:55.741 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:09:55.747 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:09:55.748 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:09:55.785 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:09:55.785 I/DeltaChat( 5586): IMAP-fetch done in 3 ms.
06-24 14:09:55.788 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:09:58.000 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:09:58.007 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:09:58.010 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:09:58.016 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:10:27.711 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:10:56.157 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:10:56.158 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:10:56.161 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:10:56.162 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:10:56.162 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:10:56.199 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:10:56.199 I/DeltaChat( 5586): IMAP-fetch done in 2 ms.
06-24 14:10:56.202 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:10:58.002 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:10:58.009 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:10:58.011 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:10:58.017 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:11:23.683 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:11:23.689 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:11:27.716 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:11:28.652 I/DeltaChat( 5586): -------------------- Activity started --------------------
06-24 14:11:28.655 I/DeltaChat( 5586): *** LaunchActivity.onResume()
06-24 14:11:56.334 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:11:56.334 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:11:56.336 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:11:56.336 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:11:56.336 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:11:56.371 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:11:56.372 I/DeltaChat( 5586): IMAP-fetch done in 9 ms.
06-24 14:11:56.373 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:11:58.002 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:11:58.006 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:11:58.008 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:11:58.010 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:12:02.562 I/DeltaChat( 5586): *** LaunchActivity.onPause()
06-24 14:12:02.739 I/DeltaChat( 5586): *** LaunchActivity.onResume()
06-24 14:12:08.110 I/DeltaChat( 5586): *** LaunchActivity.onPause()
06-24 14:12:08.912 I/DeltaChat( 5586): -------------------- Activity stopped --------------------
06-24 14:12:08.932 I/DeltaChat( 5586): *** LaunchActivity.onDestroy()
06-24 14:12:24.892 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:12:24.895 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:12:24.901 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:12:25.636 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:12:25.640 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:12:25.788 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:12:25.792 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:12:25.798 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:12:25.886 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:12:25.887 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:12:27.725 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:12:29.609 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:12:29.621 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:12:29.668 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:12:46.176 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:12:46.178 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:12:55.471 I/DeltaChat( 5586): IMAP-IDLE has data.
06-24 14:12:55.471 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:12:55.474 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:12:55.476 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:12:55.476 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:12:55.513 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:12:55.513 I/DeltaChat( 5586): IMAP-fetch done in 2 ms.
06-24 14:12:55.517 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:12:56.645 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:12:56.649 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:12:56.657 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:12:58.000 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:12:58.003 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:12:58.003 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:12:58.005 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:13:14.312 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:13:14.314 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:13:27.732 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:13:55.651 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:13:55.651 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:13:55.655 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:13:55.657 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:13:55.657 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:13:55.701 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:13:55.701 I/DeltaChat( 5586): IMAP-fetch done in 2 ms.
06-24 14:13:55.703 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:13:58.003 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:13:58.010 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:13:58.012 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:13:58.017 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:14:17.958 I/DeltaChat( 5586): -------------------- Activity started --------------------
06-24 14:14:17.963 I/DeltaChat( 5586): *** LaunchActivity.onResume()
06-24 14:14:19.671 I/DeltaChat( 5586): *** LaunchActivity.onPause()
06-24 14:14:20.370 I/DeltaChat( 5586): -------------------- Activity stopped --------------------
06-24 14:14:20.386 I/DeltaChat( 5586): *** LaunchActivity.onDestroy()
06-24 14:14:27.741 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:14:55.813 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:14:55.814 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:14:55.819 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:14:55.820 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:14:55.820 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:14:55.858 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:14:55.858 I/DeltaChat( 5586): IMAP-fetch done in 1 ms.
06-24 14:14:55.860 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:14:58.003 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:14:58.009 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:14:58.012 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:14:58.019 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:14:58.148 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:14:58.153 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:14:58.170 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:15:14.627 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:15:14.633 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:15:27.780 I/DeltaChat( 5586): -------------------- on receive timer --------------------
06-24 14:15:33.394 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:15:33.404 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:15:33.436 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()
06-24 14:15:44.476 I/DeltaChat( 5586): -------------------- Screen on --------------------
06-24 14:15:44.485 I/DeltaChat( 5586): *** KeepAliveService.onDestroy()
06-24 14:15:55.988 I/DeltaChat( 5586): IMAP-IDLE timeout.
06-24 14:15:55.989 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:15:55.991 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:15:55.992 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:15:55.992 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:15:56.036 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:15:56.036 I/DeltaChat( 5586): IMAP-fetch done in 1 ms.
06-24 14:15:56.038 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:15:58.000 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:15:58.002 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:15:58.003 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:15:58.005 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:16:27.789 I/DeltaChat( 5586): -------------------- on receive timer --------------------

06-24 14:16:55.230 I/DeltaChat( 5586): IMAP-IDLE has data.
06-24 14:16:55.231 I/DeltaChat( 5586): IMAP-IDLE ended.
06-24 14:16:55.237 I/DeltaChat( 5586): IMAP-jobs started...
06-24 14:16:55.240 I/DeltaChat( 5586): IMAP-jobs ended.
06-24 14:16:55.241 I/DeltaChat( 5586): IMAP-fetch started...
06-24 14:16:55.281 I/DeltaChat( 5586): 0 mails read from "INBOX".
06-24 14:16:55.282 I/DeltaChat( 5586): IMAP-fetch done in 4 ms.
06-24 14:16:55.288 I/DeltaChat( 5586): IMAP-IDLE started...
06-24 14:16:58.000 I/DeltaChat( 5586): SMTP-idle ended.
06-24 14:16:58.007 I/DeltaChat( 5586): SMTP-jobs started...
06-24 14:16:58.010 I/DeltaChat( 5586): SMTP-jobs ended.
06-24 14:16:58.015 I/DeltaChat( 5586): SMTP-idle started...
06-24 14:16:59.754 I/DeltaChat( 5586): -------------------- Screen off --------------------
06-24 14:16:59.760 I/DeltaChat( 5586): *** KeepAliveService.onCreate()
06-24 14:16:59.780 I/DeltaChat( 5586): *** KeepAliveService.onStartCommand()

**Comment by r10s** [comment]
closing this for now here, of course, the discussion can go on in the new support forum at https://support.delta.chat
